# Generated by Django 2.2.12 on 2021-03-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocuments',
        ),
    ]
